apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  NODE_ENV: "production"
  PORT: "5000"
  MONGODB_URI: "mongodb://tiendat:dat123@mongodb.biglab.svc.cluster.local:27017/clickcounter?authSource=clickcounter" 