apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Values.namespace }}
data:
  NODE_ENV: {{ .Values.backend.env.NODE_ENV | quote }}
  PORT: {{ .Values.backend.env.PORT | quote }}
  MONGODB_URI: {{ printf "mongodb://%s:%s@mongodb.%s.svc.cluster.local:27017/clickcounter?authSource=clickcounter" .Values.mongodb.username .Values.mongodb.password .Values.namespace | quote }}
