apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.serviceType | default "ClusterIP" }}
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: {{ .Values.backend.env.PORT }} 