apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.frontend.serviceType | default "ClusterIP" }}
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80 