apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: {{ .Values.namespace }}
data:
  REACT_APP_API_URL: "http://backend.biglab.svc.cluster.local:5000"
  NODE_ENV: "production"