apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.username | b64enc | quote }}
  password: {{ .Values.mongodb.password | required "mongodb.password is required! (do not commit secrets to git)" | b64enc | quote }}