apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
  annotations:
    # Add annotation for external-secrets-operator if using it
    external-secrets.kubernetes-client.io/secret-store: mongodb-secret-store
type: Opaque
data:
  # These will be populated by external secrets management
  # For manual setup, create the secret separately:
  # kubectl create secret generic mongodb-secret \
  #   --from-literal=username=your-username \
  #   --from-literal=password=your-password \
  #   -n {{ .Values.namespace }}
  username: {{ .Values.mongodb.username | default "PLACEHOLDER_USERNAME" | b64enc | quote }}
  password: {{ .Values.mongodb.password | default "PLACEHOLDER_PASSWORD" | b64enc | quote }}