# Development environment values
# This file should NOT contain actual secrets
# Secrets are managed externally via Kubernetes secrets or external-secrets-operator

namespace: biglab-dev

backend:
  image: tiendatdev94/click-app-backend
  tag: '49'
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
  env:
    NODE_ENV: development
    PORT: 5000
    # MongoDB URI will be constructed from secrets
    MONGODB_URI: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mongodb.${NAMESPACE}.svc.cluster.local:27017/clickcounter?authSource=clickcounter

frontend:
  image: tiendatdev94/click-app-frontend
  tag: '49'
  serviceType: ClusterIP
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

mongodb:
  image: tiendatdev94/click-app-db
  tag: '49'
  database: clickcounter
  storageClass: gp2
  storage: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi 